"""initial

Revision ID: 5288c49be301
Revises: 
Create Date: 2026-05-20 09:29:30.532700

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5288c49be301'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=128), nullable=False, comment='部门名称'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='上级部门ID'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态: True=启用 False=禁用'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_parent_id'), 'departments', ['parent_id'], unique=False)
    op.create_table('menus',
    sa.Column('name', sa.String(length=128), nullable=False, comment='菜单名称'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='上级菜单ID'),
    sa.Column('route_path', sa.String(length=255), nullable=True, comment='路由路径'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='组件路径'),
    sa.Column('icon', sa.String(length=64), nullable=True, comment='图标'),
    sa.Column('hidden', sa.Boolean(), nullable=False, comment='是否隐藏'),
    sa.Column('is_external_link', sa.Boolean(), nullable=False, comment='是否外链'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_parent_id'), 'menus', ['parent_id'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作用户ID'),
    sa.Column('username', sa.String(length=128), nullable=True, comment='操作用户名'),
    sa.Column('module', sa.String(length=64), nullable=False, comment='操作模块'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='操作类型'),
    sa.Column('target_id', sa.String(length=64), nullable=True, comment='操作目标ID'),
    sa.Column('target_name', sa.String(length=255), nullable=True, comment='操作目标名称'),
    sa.Column('ip_address', sa.String(length=64), nullable=True, comment='请求IP'),
    sa.Column('request_method', sa.String(length=16), nullable=True, comment='请求方法'),
    sa.Column('request_path', sa.String(length=512), nullable=True, comment='请求路径'),
    sa.Column('request_params', sa.Text(), nullable=True, comment='请求参数 (JSON)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='操作结果: 1=成功 0=失败'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='耗时(毫秒)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='操作时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_action'), 'operation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_operation_logs_created_at'), 'operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_logs_module'), 'operation_logs', ['module'], unique=False)
    op.create_index(op.f('ix_operation_logs_user_id'), 'operation_logs', ['user_id'], unique=False)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=128), nullable=False, comment='权限名称'),
    sa.Column('code', sa.String(length=128), nullable=False, comment='权限编码 (格式: module:sub:action)'),
    sa.Column('type', sa.Enum('MENU', 'BUTTON', 'API', name='permissiontype', length=16), nullable=False, comment='权限类型: menu/button/api'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='上级权限ID'),
    sa.Column('api_path', sa.String(length=255), nullable=True, comment='API路径 (type=api时必填)'),
    sa.Column('api_method', sa.String(length=16), nullable=True, comment='HTTP方法 (type=api时必填)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['permissions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_parent_id'), 'permissions', ['parent_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=128), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=128), nullable=False, comment='角色编码'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('system_configs',
    sa.Column('group', sa.String(length=128), nullable=False, comment='配置分组'),
    sa.Column('key', sa.String(length=128), nullable=False, comment='配置键'),
    sa.Column('value', sa.Text(), nullable=False, comment='配置值'),
    sa.Column('value_type', sa.Enum('STRING', 'INTEGER', 'BOOLEAN', 'JSON', 'SELECT', name='configvaluetype', length=16), nullable=False, comment='值类型'),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False, comment='是否敏感字段'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_group'), 'system_configs', ['group'], unique=False)
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_table('menu_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('menu_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_permissions_menu_id'), 'menu_permissions', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_permissions_permission_id'), 'menu_permissions', ['permission_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=128), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='密码哈希'),
    sa.Column('nickname', sa.String(length=128), nullable=True, comment='昵称'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='手机号'),
    sa.Column('avatar', sa.String(length=512), nullable=True, comment='头像URL'),
    sa.Column('department_id', sa.BigInteger(), nullable=True, comment='部门ID'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态: True=启用 False=禁用'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否超级管理员'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否逻辑删除'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_menu_permissions_permission_id'), table_name='menu_permissions')
    op.drop_index(op.f('ix_menu_permissions_menu_id'), table_name='menu_permissions')
    op.drop_table('menu_permissions')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_group'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_parent_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_operation_logs_user_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_module'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_created_at'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_action'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_menus_parent_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_departments_parent_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
